project:
  type: website

website:
  title: "A Comparison of Multilayer Perceptron and VGG-16 Models for Fashion Image Classification"

format:
  html:
    toc: true
    execute:
      eval: false
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    filters:
      - quarto
      - filters/wrap-cell-output.lua
    css:
      - styles/main.css
